### ISSUE TITLE
[orm] where('col_name -> Nil) condition is removed

### ISSUE THREAD

**Issue by yamitzky** [skinny-framework/skinny-framework#229]
This is behavioral (feature?) request.

In Skinny-ORM, when a condition is specifying ```Nil``` to ```where```'s second term, the condition is removed(ignored).

For example, 

```scala
Company.where('id -> Nil).apply()
```
is same as

```scala
Company.apply()
```

which means, it fetches all table instead of empty result.

I think this behavior is not natural for these reasons.

1. developer must concern query is empty or not.
2. there seems to be no spec for this.(sorry if there is.)
3. different from scalikejdbc's ```in``` clause.
4. different from ActiveRecord's ```where```.

In addition to that, it was introduced after the commit 56495db870122bda1c77f32e4f0b52b97677d80a (Fixed invalid eager loading for PostgreSQL when ids is empty).

Can you change this behavior?

**Comment by seratch** [comment]
Thanks. This should be fixed.

**Comment by seratch** [comment]
Thank you for your report. Next version will be out within a few days. If you're in a hurry, please let me know.
