### ISSUE TITLE
scss compilation running in production mode

### ISSUE THREAD

**Issue by rinoguchi** [skinny-framework/skinny-framework#235]
Unintentionally, scss compilation runs in production mode, becase else condition is absent.
See the code below.

https://github.com/skinny-framework/skinny-framework/blob/develop/assets/src/main/scala/skinny/controller/AssetsController.scala#L51-L52

**Comment by seratch** [comment]
Thank you so much. 

If you have time, please make a pull request to fix this. If so, we can count your contribution here. https://github.com/skinny-framework/skinny-framework/graphs/contributors
