### ISSUE TITLE
how to get the last insert id from orm ?

### ISSUE THREAD

**Issue by jackywyz** [skinny-framework/skinny-framework#299]
how to get the last insert id from orm ?

**Comment by seratch** [comment]
```scala
scala> val c = Company.defaultAlias
c: skinny.orm.Alias[model.Company] = QuerySQLSyntaxProvider(model.Company$@293f70dd,c)

scala> Company.limit(1).orderBy(c.id.desc).apply().headOption.map(_.id)
res9: Option[Long] = Some(3)
```

**Comment by seratch** [comment]
If you mean the auto-generated id retrieval when insertion, Skinny ORM's createXXX methods basically return id value. https://github.com/skinny-framework/skinny-framework/blob/1.3.20/orm/src/main/scala/skinny/orm/feature/CRUDFeature.scala#L267-L269

**Comment by jackywyz** [comment]
this is ok ,thanks!
