### ISSUE TITLE
possible conflict on DB client libraries yields wrong boolean value

### ISSUE THREAD

**Issue by ryochin** [skinny-framework/skinny-framework#305]
I've found a weird issue of presumably client library conflict on both MySQL and MariaDB.

* Scala 2.11.7
* Skinny-ORM 1.3.20, 2.0.2
* MySQL 5.7.10

When you load mysql-connector-java and mariadb-java-client at the same time in your build.sbt,

```scala
  "mysql"            %  "mysql-connector-java" % "5.1.38",
  "org.mariadb.jdbc" %  "mariadb-java-client"  % "1.3.3",
```

`true' would be returned despite the actual column value is 0 (tinyint).

```
+------+------+
| id   | flag |
+------+------+
|    1 |    0 |
+------+------+
1 row in set (0.00 sec)
```

```scala
Book.where('id -> 1).apply().head.flag    // true !
```

When only mysql-connector-java, you'll get `false' accurately.

```scala
  "mysql"            %  "mysql-connector-java" % "5.1.38",
```

```scala
Book.where('id -> 1).apply().head.flag    // false
```

It seems OK on Scalike-JDBC layer as well. I'd like others to avoid this unfortunate trouble beforehand if possible.

I've set up minimal reproduction project so please give it a try. (and you will also find out that the second run on sbt shell would produce correct result)
[github.com/ryochin/orm-test](https://github.com/ryochin/orm-test)

**Comment by seratch** [comment]
How about opening an issue here? 

>Tracker link https://mariadb.atlassian.net/projects/CONJ/issues/

https://github.com/MariaDB/mariadb-connector-j

**Comment by seratch** [comment]
@ryochin I think this is not Skinny ORM's issue but mariadb-connector-j's one. At least, we don't have any plan to work on this issue now. Do you mind closing this issue?

**Comment by ryochin** [comment]
I see, thx anyway.
