### ISSUE TITLE
skinny-http-client can not parse `Set-Cookie` what contains path atribute

### ISSUE THREAD

**Issue by gakuzzzz** [skinny-framework/skinny-framework#312]
https://github.com/skinny-framework/skinny-framework/blob/99b1072bbe9c0b7ecfa903c9152a3d0e02ce444d/http-client/src/main/scala/skinny/http/HTTP.scala#L194-L195

```scala
            setCookie.split("=") match {
              case Array(name, _) => Some(name -> setCookie)
```

When `setCookie` contains `path` like as `Set-Cookie: foo=bar; path=/; HttpOnly`,
`setCookie.split("=")` returns an array that has 3 elements. `Array("foo", "bar; path", "/; HttpOnly")`

Should it `split("=", 2)` ?

**Comment by seratch** [comment]
Thank you. If you have time, please fix this :bow:
I will be able to immediately do the next patch release.

**Comment by xuwei-k** [comment]
FYI

- https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-1.9.36/src/main/java/com/ning/http/client/cookie/CookieDecoder.java#L26-L144
- https://github.com/scalaj/scalaj-http/blob/2.2.1/src/main/scala/scalaj/http/Http.scala#L194-L195

**Comment by seratch** [comment]
Thank you. The code just failed to extract cookie names and return the header value as-is. Just fixing it as @gakuzzzz suggested should be enough in this case.
