### ISSUE TITLE
implicit ParameterBinderFactory/Binders not being used as expected

### ISSUE THREAD

**Issue by emanresusername** [skinny-framework/skinny-framework#330]
the core of the problem scenario and some code snippets are [here](https://github.com/lloydmeta/enumeratum/issues/37) with a possible upstream fix lead [here](https://github.com/scalikejdbc/scalikejdbc/issues/530) . but even with those issues resolved. all variations of
```scala
Model.udpateById(id).withAttributes('specialType -> SpecialType.Free)
Model.findById(id).foreach(_.copy(specialType = Option(SpecialType.Beer)).save)
// etc . . .
```
give me the following error
```text
[run-main-0] ERROR scalikejdbc.StatementExecutor$$anon$1 - SQL execution failed (Reason: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'specialType' at row 1):
```
i can't seem to step into the same lines that show up in the [stack trace](http://pastebin.com/jb1pBnU3), so not sure if some of the magic is happening in macros or different thread pools, or what, but my best guess was it's something like what's going on [here](https://github.com/skinny-framework/skinny-framework/blob/2.1.1/framework/src/main/scala/skinny/session/jdbc/SkinnySession.scala#L168)

**Comment by seratch** [comment]
The pair, Symbol and value, doesn't support ParameterBinderFactory's type-safety. If you need more type-safety, consider directly using ScalikeJDBC's QueryDSL more.

**Comment by emanresusername** [comment]
if i wanted to attempt a PR to make the `Model#save` functionality work in this situation, is there a particularly good place to start looking in the code base here? Was i on the right track with the `toSerializeable` function or would work need to happen at the scalike-jdbc layer first?

**Comment by seratch** [comment]
I'm afraid that it's impossible to enable ParameterBinderFactory without introducing breaking changes to skinny-orm APIs. I don't have a plan to do that at least in the near future.

**Comment by emanresusername** [comment]
ok cool, that's fair
