### ISSUE TITLE
Increasing HTTP Read Timeout

### ISSUE THREAD

**Issue by abhinav812** [skinny-framework/skinny-framework#368]
Hi,
I'm trying to increase the defaultReadTimeoutMillis in http-client. Because i'm getting a constant read timeout after 5 sec.
How can I do it. I tried below , but didn't worked out.
HTTP.defaultReadTimeoutMillis = 6000

~
Thanks

**Comment by seratch** [comment]
You can instantiate `HTTP` to configure it.

```scala
val http = new HTTP()
http.defaultConnectTimeoutMillis = 6000
```

**Comment by abhinav812** [comment]
Thanks..
I also found a way to increase the timeout for any specific `request`..
`
request.readTimeoutMillis(6000)
`
