### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by convcha** [skinny-framework/skinny-framework#435]
Hi,
The [website](http://skinny-framework.org) seems to be down, can you please fix it?

http://skinny-framework.org
![image](https://user-images.githubusercontent.com/3993599/128028324-dd71df2b-f28a-4992-b0b8-5c234bf5e775.png)

**Comment by xuwei-k** [comment]
https://github.com/skinny-framework/skinny-framework.github.io/issues/45

**Comment by convcha** [comment]
@xuwei-k Thanks!
