### ISSUE TITLE
scala-parser-combinators dependency conflicts with latest version of scalikejdbc

### ISSUE THREAD

**Issue by gavares** [skinny-framework/skinny-framework#436]
Trying to use:

`org.scalikejdbc:scalikejdbc-core_2.13:4.0.0`

and

`org.skinny-framework:skinny-orm:3.1.0`

In the same project gives errors at sbt project initialization time:

```
[error] (orgsSvr / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-parser-combinators_2.13:2.1.0 (early-semver) is selected over 1.1.2
[error] 	    +- org.scalikejdbc:scalikejdbc-core_2.13:4.0.0        (depends on 2.1.0)
[error] 	    +- com.github.sh4869:semver-parser-scala_2.13:0.0.6   (depends on 2.1.0)
[error] 	    +- org.skinny-framework:skinny-common_2.13:3.1.0      (depends on 1.1.2)
[error]
[error]
```

I suppose this is because there hasn't been a 4.0 release for skinny-orm.

**Comment by seratch** [comment]
@gavares Thanks for taking the time to report this issue. Yeah, this project should release a new version. I will work on it shortly

**Comment by seratch** [comment]
skinny-orm v4.0.0 should work for you! https://github.com/skinny-framework/skinny-framework/releases/tag/4.0.0
